#version: '3.8'

services:
  drupal3:
    image: drupal:latest
    ports:
      - "20200:80"
    volumes:
      - drupal_data3:/var/www/html
    environment:
      - DRUPAL_DB_HOST=mysql3
      - DRUPAL_DB_NAME=${MYSQL_DATABASE}
      - DRUPAL_DB_USER=${MYSQL_USER}
      - DRUPAL_DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis3
      - REDIS_PORT=6379
    depends_on:
      - mysql3
      - redis3
    networks:
      - kelassir-drupal3-net

  mysql3:
    image: mysql:8.0
    ports:
      - "20201:3306"
    volumes:
      - mysql_data3:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - kelassir-drupal3-net

  phpmyadmin3:
    image: phpmyadmin/phpmyadmin
    ports:
      - "20202:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql3
    networks:
      - kelassir-drupal3-net

  redis3:
    image: redis:latest
    ports:
      - "20203:6379"
    networks:
      - kelassir-drupal3-net

  redis_insight3:
    image: redis/redisinsight:latest
    volumes:
       - redis_insight_data3:/db
    ports:
      - "20204:5540"
    depends_on:
      - redis3
    networks:
      - kelassir-drupal3-net

  
volumes:
  drupal_data3:
  mysql_data3:
  redis_insight_data3:

networks:
  kelassir-drupal3-net:
    driver: bridge
